package com.ruoyi.ai.domain.vo;

import java.util.ArrayList;
import java.util.List;

/**
 * Chat result generated by provider.
 */
public class AiChatResult
{
    private Long conversationId;
    private String content;
    private List<AiChatEvent> events = new ArrayList<AiChatEvent>();

    public AiChatResult()
    {
    }

    public AiChatResult(Long conversationId, String content)
    {
        this.conversationId = conversationId;
        this.content = content;
    }

    public Long getConversationId()
    {
        return conversationId;
    }

    public void setConversationId(Long conversationId)
    {
        this.conversationId = conversationId;
    }

    public String getContent()
    {
        return content;
    }

    public void setContent(String content)
    {
        this.content = content;
    }

    public List<AiChatEvent> getEvents()
    {
        return events;
    }

    public void setEvents(List<AiChatEvent> events)
    {
        this.events = events;
    }
}
